name: Deploy to Cloud Repo
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cloud-repo-deployment:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kosdev-code/kos-buildpublish/kos_builder:dockerimage
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
          lfs: true

      - name: Build and Publish
        env:
          KOSBUILD_SECRET_URL: ${{ secrets.KOSBUILD_SECRET_URL }}
          KOSBUILD_SECRET_PASSWORD: ${{ secrets.KOSBUILD_SECRET_PASSWORD }}

        working-directory: ./${{ github.event.repository.name }}
        run: kos_build_handler.sh automation .github/cloud-deployment.json